apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: faiz792/nodejs-app:IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 5000
